version: "3.8"
services:
  backend:
    build: ./backend
    container_name: node-api
    ports:
      - 3001:3001
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - 3000:3000
    links:
      - "backend:be"